### ISSUE TITLE
vmss quick-create doesn't work

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#1]
Tried to do 'azure vmss quick-create', but it threw an error saying the resource group name can't be null/undefined and must be of type string. I tried once with an existing RG, once with the name of a new RG. Screenshot attached. Expected behavior is for this command to succeed :)

![image](https://cloud.githubusercontent.com/assets/1448593/13264374/b83d952c-da22-11e5-8857-56b4766e6207.png)

**Comment by huangpf** [comment]
OK. Will fix this one.

**Comment by huangpf** [comment]
fixed.

```
azure vmss quick-create
info:    Executing command vmss quick-create
resource-group-name: x
name: x
location: x
admin-username: x
admin-password: *
Confirm password: *
ImageURN (format: "publisherName:offer:skus:version"): w:x:y:z
The provided location 'x' is not available for ...
```

**Comment by sauryadas** [comment]
Looks good.

C:\WINDOWS\system32>azure vmss quick-create mmResGrp publiciptestl westus canonical:Ubuntu_Snappy_Core_Docker:15.04:2015.0828.2346 azureuser Password1@
info: Executing command vmss quick-create

Looking up the NIC "publi-westu-2382755760-nic" info: An nic with given name "publi-westu-2382755760-nic" not found, creating a new one
Looking up the virtual network "publi-westu-2382755760-vnet" info: Preparing to create new virtual network and subnet \ Creating a new virtual network "publi-westu-2382755760-vnet" [address prefix: "10.0.0.0/16"] with subnet "publi-westu-2382755760-s+et" [address prefix: "10.0.1.0/24"]
Looking up the virtual network "publi-westu-2382755760-vnet"
Looking up the subnet "publi-westu-2382755760-snet" under the virtual network "publi-westu-2382755760-vnet" info: Found public ip parameters, trying to setup PublicIP profile
Looking up the public ip "publi-westu-2382755760-pip" info: PublicIP with given name "publi-westu-2382755760-pip" not found, creating a new one
Creating public ip "publi-westu-2382755760-pip"
Looking up the public ip "publi-westu-2382755760-pip"
Creating NIC "publi-westu-2382755760-nic"
Looking up the NIC "publi-westu-2382755760-nic" data: { data: id: '/subscriptions/5abfd9c4-ec8c-4db9-acd4-c762dce93508/resourceGroups/mmResGrp/providers/Microsoft.Compute/virtualMachineScaleSets/publiciptestl', data: name: 'publiciptestl', data: type: 'Microsoft.Compute/virtualMachineScaleSets', data: location: 'westus', data: sku: { data: name: 'Standard_D1', data: tier: 'Standard', data: capacity: 5 data: }, data: upgradePolicy: { mode: 'Manual' }, data: virtualMachineProfile: { data: osProfile: { data: computerNamePrefix: 'publiciptestl', data: adminUsername: 'azureuser', data: linuxConfiguration: { disablePasswordAuthentication: false }, data: secrets: [] data: }, data: storageProfile: { data: imageReference: { data: publisher: 'canonical', data: offer: 'Ubuntu_Snappy_Core_Docker', data: sku: '15.04', data: version: '2015.0828.2346' data: }, data: osDisk: { data: name: 'publi-westu-2382755760-os-disk', data: caching: 'ReadOnly', data: createOption: 'FromImage', data: vhdContainers: [ data: 'https://publiciptestlsto23827557.blob.core.windows.net/publi-westu-2382755760-disk-container', data: 'https://publiciptestlsto12382755.blob.core.windows.net/publi-westu-2382755760-disk-container', data: 'https://publiciptestlsto22382755.blob.core.windows.net/publi-westu-2382755760-disk-container', data: 'https://publiciptestlsto32382755.blob.core.windows.net/publi-westu-2382755760-disk-container', data: 'https://publiciptestlsto42382755.blob.core.windows.net/publi-westu-2382755760-disk-container' data: ] data: } data: }, data: networkProfile: { data: networkInterfaceConfigurations: [ data: { data: name: 'publi-westu-2382755760-nic', data: primary: true, data: ipConfigurations: [ data: { data: name: 'publi-westu-2382755760-pip', data: subnet: { id: '/subscriptions/5abfd9c4-ec8c-4db9-acd4-c762dce93508/resourceGroups/mmResGrp/providers/Microsoft.Network/virtualNetworks/publi-westu-2382755760-vnet/subnets/publi-westu-2382755760-snet' }, data: loadBalancerBackendAddressPools: [ data: { id: '/subscriptions/5abfd9c4-ec8c-4db9-acd4-c762dce93508/resourceGroups/mmResGrp/providers/Microsoft.Network/loadBalancers/publi-westu-2382755760-lb/backendAddressPools/publi-westu-2382755760-be' } data: ], data: loadBalancerInboundNatPools: [ data: { id: '/subscriptions/5abfd9c4-ec8c-4db9-acd4-c762dce93508/resourceGroups/mmResGrp/providers/Microsoft.Network/loadBalancers/publi-westu-2382755760-lb/inboundNatPools/publi-westu-2382755760-nat' } data: ] data: } data: ] data: } data: ] data: } data: }, data: provisioningState: 'Succeeded' data: } 

info: vmss quick-create command OK
