### ISSUE TITLE
vmss create-or-update doesn't work

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#10]
Just tried 'azure vmss create-or-update'. It should prompt me for resource group and the like. Instead it just errors out immediately, complaining about an unexpected token u

![image](https://cloud.githubusercontent.com/assets/1448593/13367218/b21fdf4a-dc95-11e5-9bd5-ad74e1768707.png)

**Comment by sauryadas** [comment]
Apparently we do not prompt for some commands. Users are supposed to enter it in the command itself instead of waiting to be prompted. I will create an uber bug and close this.
