### ISSUE TITLE
vmss delete should prompt instead of erroring

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#11]
I did 'vmss delete', which should have prompted me for resource group, vmss name, etc; instead it errored out:

![image](https://cloud.githubusercontent.com/assets/1448593/13369754/bb99e1d4-dcad-11e5-9bc3-b73998b02e2e.png)

**Comment by gatneil** [comment]
This is actually not just delete; it's a bunch of different commands (e.g. vmss get-instance-view)

**Comment by sauryadas** [comment]
Apparently we do not prompt for some commands. Users are supposed to enter it in the command itself instead of waiting to be prompted. I will create an uber bug and close this.
