### ISSUE TITLE
Not being prompted for certain commands for input parameters

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#12]
Errors out when the user expects to be prompted for the mandatory input parameters. Apparently some commands do prompt and others do not. How does a user know ?

**Comment by huangpf** [comment]
Fixed.

Prompt:

```
azure vmss list
info:    Executing command vmss list
resource-group-name : XPLATTSTVMSSGCREATE3372
data:    ResourceGroupName        Name            ProvisioningState  Location
data:    -----------------------  --------------  -----------------  --------------
data:    XPLATTSTVMSSGCREATE3372  xplattestvmss5  Creating           northcentralus
info:    vmss list command OK
```

Non-prompt:

```
azure vmss list XPLATTSTVMSSGCREATE3372
info:    Executing command vmss list
data:    ResourceGroupName        Name            ProvisioningState  Location
data:    -----------------------  --------------  -----------------  --------------
data:    XPLATTSTVMSSGCREATE3372  xplattestvmss5  Creating           northcentralus
info:    vmss list command OK
```

**Comment by sauryadas** [comment]
Tried a few .. looks good

![image](https://cloud.githubusercontent.com/assets/15387759/13590931/e903ef78-e498-11e5-8357-f4d0c1b97a78.png)

![image](https://cloud.githubusercontent.com/assets/15387759/13593225/4a4d5944-e4ae-11e5-969b-eb8cd24efa02.png)

![image](https://cloud.githubusercontent.com/assets/15387759/13593317/f78aab0c-e4ae-11e5-8d3f-9e94b29e1d10.png)
