### ISSUE TITLE
Change descriptions of all commands

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#15]
I am working on it now and will attach a document with the new text soon. Examples below:

help:    **Delete ->** Commands to manage your virtual machine scale sets by the deallocate method.
**Add-> *_Shutdown and release resources in a VM Scale Set
help:      vmss deallocate [options] <resource-group-name> <vm-scale-set-name> <instance-ids>
help:
help:    *_Delete ->**Commands to manage your virtual machine scale sets by the delete method.
*_Add-> *_Delete a VM Scale Set
help:      vmss delete [options] <resource-group-name> <vm-scale-set-name>

**Comment by huangpf** [comment]
Help documentation is owned by PM. For revising messages, please go to the following swagger spec repo, and send PRs there for update:
https://github.com/Azure/azure-rest-api-specs

**Comment by sauryadas** [comment]
Yes i will do my part sometime soon. Please make sure that your code that picks up these messages are picked up from the swagger spec.

**Comment by huangpf** [comment]
@sauryadas OK. Also, please note that Swagger specs are used to build client libraries. So, don't include the key word `Command` to it, which doesn't apply to client library functions.

Try to write up some generic help messages to describe the 'functionality', i.e. as what you wrote:

```
Shutdown and release resources in a VM Scale Set
```

**Comment by sauryadas** [comment]
@huangpf @amarzavery - I am trying to make a PR to this repository 'azure-rest-api-specs' and am getting the following error. Can you please grant me access?

![image](https://cloud.githubusercontent.com/assets/15387759/13895535/6afefc8e-ed31-11e5-9fa6-d0253c5543b7.png)

**Comment by amarzavery** [comment]
@sauryadas - azure-rest-api-specs is a public repo. You should have access to it. From the image it looks like you are trying to push your changes directly to the Azure/azure-rest-api-specs repo. That is not allowed. Please send a pull request.

**Comment by amarzavery** [comment]
from your fork to Azure/azure-rest-api-specs repo.

**Comment by sauryadas** [comment]
Hyonho checked in
