### ISSUE TITLE
vmss list-skus command is confusing

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#17]
talked to Amol from the VMSS dev team. This command has got nothing to do with a users resource group and VMSS. Its intent is to display sku's supported for a specific subscription. At this point all SKU's are supported for all subscriptions. Not clear why and when they would not.

We should get rid of this:
vmss list-skus [options] <resource-group-name> <vm-scale-set-name>

OR rename to 
Allows you to view SKU's available for VMSS
vmss list-skus [options] 
Options:
help:      -h, --help                                       output usage information
help:      -v, --verbose                                    use verbose output
help:      -vv                                              more verbose with debug output
help:      --json                                           use json output
help:      -s, --subscription <subscription>                the subscription identifier

**Comment by huangpf** [comment]
I'm confused by the help messages. The one I got is as follows, and it takes RG name and VMSS name:

```
Usage: vmss list-skus [options] <resource-group-name> <vm-scale-set-name>
```

Let's assume this statement is true `At this point all SKU's are supported for all subscriptions`, but, as required by the API, if users have no RGs or VMSS in the subscription, this API still won't work, no matter how.

**Comment by huangpf** [comment]
Maybe `No-API+support` is a good tag for this case.

**Comment by sauryadas** [comment]
@huangpf need to hide this and let customer ask for it. thoughts?

**Comment by huangpf** [comment]
I think it can be left as is...

**Comment by sauryadas** [comment]
just leave it as is for now ... will need to find out a way to educate users on why this command is in place.
