### ISSUE TITLE
data: null after successfully running vmssvm power-off/restart/start commands

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#19]
Why are we showing the data: null?

![image](https://cloud.githubusercontent.com/assets/15387759/13518007/315f3e12-e17e-11e5-9c23-1a2e2e11179a.png)

**Comment by huangpf** [comment]
fixed. Please check out the latest build.

**Comment by sauryadas** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/15387759/13590879/8f49b17a-e498-11e5-9671-b9bb9cccbba1.png)
