### ISSUE TITLE
quick-create with ssh requires password

### ISSUE THREAD

**Issue by SorraTheOrc** [sauryadas/Azure-CLI-VMSS#32]
In #31 reports missing required params in the --help, a ssh-key is provided then those params (which were requested interactively in the non-ssh-key version) are required.

$ azure vmss quick-create --help
help:    Commands to create a virtual machine scale set with default resources in a group.
help:
help:    Usage: vmss quick-create [options] <resource-group-name> <name> <location> <image-urn> [admin-username] [admin-password]
help:
help:    Options:

$ azure vmss quick-create rgvmsstest rgvmsstest westus canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201603180 -M ~/.ssh/id_rsa.pub
info:    Executing command vmss quick-create
- Looking up the NIC "rgvms-westu-2598221543-nic"
  info:    Found an existing NIC "rgvms-westu-2598221543-nic"
  info:    Found an IP configuration with virtual network subnet id "/subscriptions/325e7c34-99fb-4190-aa87-1df746c67705/resourceGroups/rgvmsstest/provide
  rs/Microsoft.Network/virtualNetworks/rgvms-westu-2598221543-vnet/subnets/rgvms-westu-2598221543-snet" in the NIC "rgvms-westu-2598221543-nic"
  info:    This NIC IP configuration is already configured with the provided public ip "rgvms-westu-2598221543-pip"
  error:   Required parameter 'adminUsername' is missing (null).
  info:    Error information has been recorded to /home/rgardler/.azure/azure.err
  error:   vmss quick-create command failed

$ azure vmss quick-create rgvmsstest rgvmsstest westus canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201603180 -u azureuser -M ~/.ssh/id_rsa.pub
info:    Executing command vmss quick-create
- Looking up the NIC "rgvms-westu-2598221543-nic"
  info:    Found an existing NIC "rgvms-westu-2598221543-nic"
  info:    Found an IP configuration with virtual network subnet id "/subscriptions/325e7c34-99fb-4190-aa87-1df746c67705/resourceGroups/rgvmsstest/provid$
  rs/Microsoft.Network/virtualNetworks/rgvms-westu-2598221543-vnet/subnets/rgvms-westu-2598221543-snet" in the NIC "rgvms-westu-2598221543-nic"
  info:    This NIC IP configuration is already configured with the provided public ip "rgvms-westu-2598221543-pip"
  error:   Required parameter 'adminPassword' is missing (null).
  info:    Error information has been recorded to /home/rgardler/.azure/azure.err
  error:   vmss quick-create command failed

$ azure vmss quick-create rgvmsstest rgvmsstest westus canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201603180 -u azureuser -M ~/.ssh/id_rsa.pub -p Pa$
$w0rd
info:    Executing command vmss quick-create
...
info:    vmss quick-create command OK

**Comment by sauryadas** [comment]
@huangpf - password should not be required if a ssh key is provided

**Comment by huangpf** [comment]
@sauryadas I can't reproduce this. Could you please try the latest `AzureRT:dev` build?

**Comment by huangpf** [comment]
```
azure vmss quick-create -h
help:    Commands to create a virtual machine scale set with default resources in a group.
help:
help:    Usage: vmss quick-create [options] <resource-group-name> <name> <location> <image-urn> <capacity> <admin-username> [admin-password]
```

```
azure vmss quick-create a a mars a:a:a:a 1000000 u --ssh-publickey-file a
info:    Executing command vmss quick-create
error:   The provided location 'mars' is not available for resource group. List of available regions is ',centralus,eastasia,southeastasia,eastus...
```

**Comment by sauryadas** [comment]
@huangpf - Does not prompt for password anymore. Thanks!

<img width="1320" alt="screen shot 2016-03-22 at 1 31 50 pm" src="https://cloud.githubusercontent.com/assets/15387759/13967104/ba3fc91e-f032-11e5-8a10-a27bae9d7288.png">
