### ISSUE TITLE
documentation for acquiring a URN for quick-creation

### ISSUE THREAD

**Issue by jluk** [sauryadas/Azure-CLI-VMSS#33]
When trying to quick-create, it is unnecessarily difficult to find an image URN to create off of. Learning from @sauryadas there is a CLI command, but even that was difficult to find an applicable URN.

Could we
1) Receive a default URN through the CLI when creating a VMSS
2) Get some documentation for how to find a URN for the user's needs

**Comment by sauryadas** [comment]
@huangpf i cannot find this command in the compute.json file where i am updating all help text.

I plan on adding the following. Can you please guide me to the file where i can update this?

For 'image-urn' refer the following command: $ azure vm image list <location> <publisher> (Example: $ azure vm image list westus canonical)

**Comment by huangpf** [comment]
This part is controlled by us in the manually written command.

**Comment by huangpf** [comment]
Fixed. @sauryadas Could you please add me to the repo contributor so that I can label the issue?

**Comment by sauryadas** [comment]
@huangpf i made you a collaborator .. hopefully you can label and close issues

**Comment by sauryadas** [comment]
@jluk Please close this if you see this as fixed.

**Comment by jluk** [comment]
@sauryadas what exactly am I testing here?

**Comment by sauryadas** [comment]
@jluk please install the latest azure Cli public release and see if the documentation of quick-create is helpful in figuring out the urn or not . Thanks !

**Comment by jluk** [comment]
@sauryadas I still get the same text prompts - what is the best way to update the CLI if you used the windows installer (also had trouble finding docs for that)? I went back and did the npm install to do an update from the command line but don't see any different prompts after doing that. Currently on 0.9.16

```
C:\Users\JULUK>azure vmss quick-create
info:    Executing command vmss quick-create
resource-group-name: jlgroup1
name: jlvmss
location: westus
admin-username: jluk
admin-password: ********
Confirm password: ********
ImageURN (format: "publisherName:offer:skus:version"): canonical
error:   --image-urn must be in the form "publisherName:offer:skus:version"
info:    Error information has been recorded to C:\Users\JULUK\.azure\azure.err
error:   vmss quick-create command failed
```

**Comment by sauryadas** [comment]
@jluk I see that the help text has been updated. Does that help?

![image](https://cloud.githubusercontent.com/assets/15387759/14306604/89d9edda-fb7d-11e5-8033-f5e5c80c1521.png)
![image](https://cloud.githubusercontent.com/assets/15387759/14306624/b476d77e-fb7d-11e5-98dd-12cabd7cf7c3.png)
