### ISSUE TITLE
quick-create with ssh requests password to login

### ISSUE THREAD

**Issue by SorraTheOrc** [sauryadas/Azure-CLI-VMSS#35]
As reported in #32 quick-create forces a password. Once created a password is required in order to login and I can't figure out what password to use, it's certainly not the one provided in the CLI command (my key does not have a password).

$ azure vmss quick-create rgvmsstest rgvmsstest westus canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201603180 -u azureuser -M ~/.ssh/id_rsa.pub -p Pa$$w0rd
 info: Executing command vmss quick-create
 ...
 info: vmss quick-create command OK

$ azure vmss quick-create rgvmsstest rgvmsstest westus canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201603180 -u azureuser -M ~/.ssh/id_rsa.pub -p Pa$
 $w0rd
 info: Executing command vmss quick-create
 ...
 info: vmss quick-create command OK

**Comment by sauryadas** [comment]
@huangpf - no password should be needed to ssh.

**Comment by huangpf** [comment]
In this case, either one can be used. What does the output `azure vmss get -vv` show?

**Comment by sauryadas** [comment]
This is fixed now.
