### ISSUE TITLE
Quick-create needs to prompt for capacity

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#36]
@huangpf - Feedback from users

Feedback 1:
-   Nice experience on vmss quick-create, can we look into making this command prompt for instance count (capacity) as opposed to creating a default of 5?

data:        sku: {
data:            name: 'Standard_D1',
data:            tier: 'Standard',
data:            capacity: 5
data:        },

Feedback 2:

I’m leaning towards having instance count as a required parameter, mostly because it’s a fundamental property of a scale set that we want people to consciously choose

@singhkay - Can you please do the same for PS?

**Comment by huangpf** [comment]
If VMSS is meant to be scaled up and down easily, it's OK to have a default capacity, and this was the design thought we went back and forth since the beginning. If it's not the case, we can consider require the input of this parameter.

**Comment by sauryadas** [comment]
@huangpf in addition to be able to scaled up and down easily , vmss is also meant to allow to choose the number of vms in a vmss to start with . My bad I missed this during the design .. It will be great if we can make it a required input .. Thanks

**Comment by sauryadas** [comment]
looks like fixed.

<img width="1324" alt="screen shot 2016-03-22 at 1 07 17 pm" src="https://cloud.githubusercontent.com/assets/15387759/13966465/c08fa2c4-f02f-11e5-973f-82310995f069.png">
