### ISSUE TITLE
azure vmss help order

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#38]
When i type in 'azure vmss', I get the list of commands below; it seems everything is in alphabetical order, except for quick-create, which is at the end of the list; from a consistency perspective, all of it should be in alphabetical order (or, if we want to make quick-create stand out, then it should be at the top, perhaps after the config commands)

![capture](https://cloud.githubusercontent.com/assets/1448593/13940638/949619de-ef9c-11e5-98a1-e9964903a1a7.PNG)

**Comment by sauryadas** [comment]
@gatneil duplicate if #21 This has been discussed at length over email.

**Comment by huangpf** [comment]
This is by design, as it's sorted by (invisible) code files...

**Comment by sauryadas** [comment]
sorted by alphabetical order.
