### ISSUE TITLE
Confusing almost identical commands

### ISSUE THREAD

**Issue by AlanSt** [sauryadas/Azure-CLI-VMSS#4]
I have not seen in any other area a 'list', 'list-next', 'list-all', and 'list-all-next'.  What are these things?  Why when I list wouldn't I want to list all?  There are a couple examples of this type of thing, don't know what they're trying to tell me.

**Comment by huangpf** [comment]
The *next functions will be removed.

**Comment by sauryadas** [comment]
This has been fixed now. List is listing all vmsses in a resource group and list-all is listing all images in a subscription. I have made changes to help documentation to call this out.
