### ISSUE TITLE
azure vmss config sku set doesn't prompt

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#41]
When I run 'azure vmss config sku set', I expect it to prompt me for both the file and the elements of the sku. Instead, it only prompts me for the file then exits without doing anything:

![capture](https://cloud.githubusercontent.com/assets/1448593/13941130/b5afa658-efa1-11e5-87a5-e69e006a9dc6.PNG)

**Comment by gatneil** [comment]
This appears to be a general problem with other 'azure vmss config' commands as well; please fix in all of them :)

**Comment by sauryadas** [comment]
@huangpf - please take a look

**Comment by huangpf** [comment]
Please help merge and sort duplicate or related bugs for better tracking, :-)

**Comment by huangpf** [comment]
Fixed:

```
xxx\cli-dev>node bin\azure vmss config sku set
info:    Executing command vmss config sku set
parameter-file : .\test\qqq.txt
error:   ENOENT, no such file or directory 'xxx\test\qqq.txt'
info:    Error information has been recorded to xxx\.azure\azure.err
error:   vmss config sku set command failed
```

**Comment by huangpf** [comment]
I tag it as `Ready-For-Test`. Please help close the issue, once it's been verified on your end, :-) Thanks @gatneil .

**Comment by sauryadas** [comment]
closing since i havent heard from @gatneil
