### ISSUE TITLE
vmss list asks for resource group, vm list does not.

### ISSUE THREAD

**Issue by gbowerman** [sauryadas/Azure-CLI-VMSS#46]
It's very useful to be able list all the scale sets in a subscription (like you can for vm's) instead of having to iterate through resource groups. VMSS provides an API for this: https://management.azure.com/subscriptions/<subid>/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2016-03-30
so this command should have parity with the equivalent VM command.

**Comment by sauryadas** [comment]
@gbowerman  Please use azure vmss list-all command
