### ISSUE TITLE
Quick-create has no option to define the number of VM's in a VMSS

### ISSUE THREAD

**Issue by sauryadas** [sauryadas/Azure-CLI-VMSS#8]

**Comment by huangpf** [comment]
I think we talked about this when building the quick command, and the decision was to NOT expose it.

**Comment by huangpf** [comment]
Will fix this one.

**Comment by sauryadas** [comment]
this is fixed and verified.

![image](https://cloud.githubusercontent.com/assets/15387759/13799166/4b793ae0-eada-11e5-8674-28eba6d16ac4.png)

![image](https://cloud.githubusercontent.com/assets/15387759/13799170/50bfee22-eada-11e5-81ac-d899e95f24f7.png)
